### PR TITLE
added a json variable to render dynamic publications data

### PR DESCRIPTION
**Pull request by ronald-wbd**

### CODE REVIEW

**Comment by will-wbd** [comment]
@ronald-wbd here some updates for the publications page and json file

**Publications**

- [ ] Make checkbox inputs look more like the [mockup](https://www.figma.com/file/zJVcsbdGW9NDCNLDo5wdr9/VHA-Innovation-Website?type=design&node-id=295%3A2420&mode=design&t=iPnJHy9FOFnY5zHz-1) 
 
 **JSON**
- [ ] Add "Featured" article from Home Page to the json file - at the very top
- [ ] Update function to not show empty spans if there are no values. Example: Interview Type doesn't have "meta": "" or "author": "" so `<spans></span>` should not be in the html

**Comment by ronald-wbd** [comment]
Here is the latest preview link from azure: https://lemon-meadow-04fb70a10.3.azurestaticapps.net/publications

**Review by will-wbd — APPROVED** [review]
Looks good!

**Comment by will-wbd** [comment]
@ronald-wbd here are some updates for the publications page

- [ ]  Check responsive behavior of the input and search button. Are these USWDS components? If so, make sure we are importing the correct css from USWDS

**Review by will-wbd — APPROVED** [review]
@ronald-wbd Great! Please merge into 'main' and then talk with Jim about how to get this on to Sandbox 😊

**Comment by ronald-wbd** [comment]
@will-wbd Should we leave it up to you to delete branch no longer needed?

**Pull request merged**
