### PR TITLE
Team bios

### PR DESCRIPTION
**Pull request by ronald-wbd**

### CODE REVIEW

**Review by will-wbd — CHANGES_REQUESTED** [review]
Please see the following requests:

* Rename page from "Bios" to "Our Team"
* Update page background to be the same color as publications and home page. See mockup for reference 
* Align the team member image to the top and not be centered vertically 
* Double check tablet view and reference the mockup (tablet-1.png)
tablet-1
* Add alt text to images. You can add their name and title 
* Duplicate person at the bottom. Double check the word doc. I believe the last person is an inventor
duplicate
* Double check the mobile layout. Titles and team member images are not lining up like the mockup
titles-images
* Remove `<strong>` tags from `<h3>` tags please. The `<h3>` already has a bold `font-weight`
* Update the bottom padding on the team member image for the mobile layout. Please review mockup
avatar-padding

**Comment by ronald-wbd** [comment]
addressed all above requested changes... https://polite-smoke-0f3014810-58.centralus.3.azurestaticapps.net/ourteam/

**Review by will-wbd — CHANGES_REQUESTED** [review]
Thanks for the updates

Still finding some wonkiness with mobile/tablet. See screenshot
Screenshot 2023-08-15 at 11 50 36 AM

**Comment by ronald-wbd** [comment]
hi @will-wbd can we close this pull request? I've updated team-bios-2 with all updates and it also has the search box font color in the header fix along with the publication checkbox styles fixes

**Pull request closed without merging**
